#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
source_root <- if (length(args) >= 1) args[[1]] else file.path("vendor", "ggsci")
output_file <- if (length(args) >= 2) {
  args[[2]]
} else {
  file.path("crates", "ggsci", "src", "generated", "palettes.rs")
}

palette_file <- file.path(source_root, "R", "palettes.R")
if (!file.exists(palette_file)) {
  stop("palette source not found: ", palette_file, call. = FALSE)
}

env <- new.env(parent = baseenv())
sys.source(palette_file, envir = env)
if (!exists("ggsci_db", envir = env, inherits = FALSE)) {
  stop("palette source did not define ggsci_db", call. = FALSE)
}

ggsci_db <- get("ggsci_db", envir = env, inherits = FALSE)
if (!is.list(ggsci_db)) {
  stop("ggsci_db must be a list", call. = FALSE)
}

excluded_families <- c("gephi", "iterm")
continuous_families <- c("gsea", "bs5", "material", "tw3")
families <- names(ggsci_db)
families <- families[!(families %in% excluded_families)]

missing_continuous_families <- setdiff(continuous_families, families)
if (length(missing_continuous_families) > 0L) {
  stop(
    "known continuous families are missing: ",
    paste(missing_continuous_families, collapse = ", "),
    call. = FALSE
  )
}

hex_pattern <- "^#[0-9A-Fa-f]{6}$"

rust_string <- function(value) {
  escaped <- gsub("\\\\", "\\\\\\\\", value)
  escaped <- gsub("\"", "\\\\\"", escaped)
  paste0("\"", escaped, "\"")
}

rust_identifier <- function(family, variant) {
  ident <- paste(family, variant, sep = "_")
  ident <- gsub("[^A-Za-z0-9]+", "_", ident)
  ident <- gsub("_+", "_", ident)
  ident <- gsub("^_|_$", "", ident)
  ident <- toupper(ident)
  if (grepl("^[0-9]", ident)) {
    ident <- paste0("P_", ident)
  }
  ident
}

records <- list()
seen_identifiers <- character()
palette_count <- 0L
color_count <- 0L
discrete_palette_count <- 0L
discrete_color_count <- 0L
continuous_palette_count <- 0L
continuous_anchor_color_count <- 0L

for (family in families) {
  family_palettes <- ggsci_db[[family]]
  if (!is.list(family_palettes)) {
    stop("palette family is not a list: ", family, call. = FALSE)
  }

  variants <- names(family_palettes)
  for (variant in variants) {
    colors <- family_palettes[[variant]]
    if (!is.character(colors)) {
      stop("palette is not a character vector: ", family, ":", variant, call. = FALSE)
    }
    if (anyNA(colors) || any(!grepl(hex_pattern, colors))) {
      stop("palette contains invalid hex colors: ", family, ":", variant, call. = FALSE)
    }

    identifier <- rust_identifier(family, variant)
    if (identifier %in% seen_identifiers) {
      stop("duplicate generated Rust identifier: ", identifier, call. = FALSE)
    }

    seen_identifiers <- c(seen_identifiers, identifier)
    palette_count <- palette_count + 1L
    color_count <- color_count + length(colors)
    kind <- if (family %in% continuous_families) "Continuous" else "Discrete"

    if (kind == "Continuous") {
      continuous_palette_count <- continuous_palette_count + 1L
      continuous_anchor_color_count <- continuous_anchor_color_count + length(colors)
    } else {
      discrete_palette_count <- discrete_palette_count + 1L
      discrete_color_count <- discrete_color_count + length(colors)
    }

    records[[length(records) + 1L]] <- list(
      family = family,
      variant = variant,
      identifier = identifier,
      kind = kind,
      colors = toupper(substring(colors, 2L))
    )
  }
}

classified_continuous_families <- unique(vapply(
  records[vapply(records, function(record) record$kind == "Continuous", logical(1L))],
  function(record) record$family,
  character(1L)
))
unexpected_continuous_families <- setdiff(
  classified_continuous_families,
  continuous_families
)
if (length(unexpected_continuous_families) > 0L) {
  stop(
    "unexpected families classified as continuous: ",
    paste(unexpected_continuous_families, collapse = ", "),
    call. = FALSE
  )
}
if (!setequal(classified_continuous_families, continuous_families)) {
  stop("continuous family classification did not match the validated set", call. = FALSE)
}

expected_counts <- c(
  palette_count = 86L,
  color_count = 946L,
  discrete_palette_count = 33L,
  discrete_color_count = 403L,
  continuous_palette_count = 53L,
  continuous_anchor_color_count = 543L
)
actual_counts <- c(
  palette_count = palette_count,
  color_count = color_count,
  discrete_palette_count = discrete_palette_count,
  discrete_color_count = discrete_color_count,
  continuous_palette_count = continuous_palette_count,
  continuous_anchor_color_count = continuous_anchor_color_count
)
if (!identical(actual_counts, expected_counts)) {
  stop(
    "unexpected palette counts; expected ",
    paste(names(expected_counts), expected_counts, sep = "=", collapse = ", "),
    "; got ",
    paste(names(actual_counts), actual_counts, sep = "=", collapse = ", "),
    call. = FALSE
  )
}

lines <- c(
  "// Generated by tools/generate-palettes.R from ggsci/R/palettes.R.",
  "// Do not edit by hand.",
  "// Color literals intentionally preserve the canonical 0xRRGGBB source form.",
  "#![allow(clippy::unreadable_literal)]",
  "",
  "use crate::{Palette, PaletteKind, Rgb};",
  "",
  paste0("pub(crate) const PALETTE_COUNT: usize = ", palette_count, ";"),
  paste0("pub(crate) const COLOR_COUNT: usize = ", color_count, ";"),
  paste0(
    "pub(crate) const DISCRETE_PALETTE_COUNT: usize = ",
    discrete_palette_count,
    ";"
  ),
  paste0(
    "pub(crate) const DISCRETE_COLOR_COUNT: usize = ",
    discrete_color_count,
    ";"
  ),
  paste0(
    "pub(crate) const CONTINUOUS_PALETTE_COUNT: usize = ",
    continuous_palette_count,
    ";"
  ),
  paste0(
    "pub(crate) const CONTINUOUS_ANCHOR_COLOR_COUNT: usize = ",
    continuous_anchor_color_count,
    ";"
  ),
  "pub(crate) const DATA_SOURCE: &str = \"ggsci/R/palettes.R\";",
  ""
)

for (record in records) {
  lines <- c(lines, paste0("const ", record$identifier, ": &[Rgb] = &["))
  color_lines <- paste0("    Rgb::from_hex(0x", record$colors, "),")
  lines <- c(lines, color_lines, "];", "")
}

lines <- c(lines, "pub(crate) static PALETTES: &[Palette] = &[")
for (record in records) {
  lines <- c(
    lines,
    paste0(
      "    Palette::new(",
      rust_string(record$family),
      ", ",
      rust_string(record$variant),
      ", PaletteKind::",
      record$kind,
      ", ",
      record$identifier,
      "),"
    )
  )
}
lines <- c(lines, "];", "")

dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_file, useBytes = TRUE)

message(
  "generated ", palette_count, " palettes and ", color_count, " stored colors (",
  discrete_palette_count, " discrete / ", continuous_palette_count, " continuous)"
)
