#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
source_root <- if (length(args) >= 1L) args[[1L]] else file.path("vendor", "ggsci")
output_file <- if (length(args) >= 2L) {
  args[[2L]]
} else {
  file.path("crates", "ggsci", "tests", "generated", "continuous_fixtures.rs")
}

continuous_families <- c("gsea", "bs5", "material", "tw3")
sample_counts <- c(0L, 1L, 2L, 3L, 7L, 30L, 512L)
representative_variants <- c(
  gsea = "default",
  bs5 = "blue",
  material = "blue-grey",
  tw3 = "slate"
)
required_files <- c(
  "DESCRIPTION",
  file.path("R", "palettes.R"),
  file.path("R", paste0("continuous-", continuous_families, ".R"))
)
missing_files <- required_files[!file.exists(file.path(source_root, required_files))]
if (length(missing_files) > 0L) {
  stop(
    "continuous fixture sources are missing: ",
    paste(missing_files, collapse = ", "),
    call. = FALSE
  )
}

env <- new.env(parent = baseenv())
env$colorRamp <- grDevices::colorRamp
env$rgb <- grDevices::rgb
sys.source(file.path(source_root, "R", "palettes.R"), envir = env)
for (family in continuous_families) {
  sys.source(
    file.path(source_root, "R", paste0("continuous-", family, ".R")),
    envir = env
  )
}

if (!exists("ggsci_db", envir = env, inherits = FALSE)) {
  stop("palette source did not define ggsci_db", call. = FALSE)
}
ggsci_db <- env$ggsci_db
hex_rgb_pattern <- "^#[0-9A-Fa-f]{6}$"
hex_rgba_pattern <- "^#[0-9A-Fa-f]{8}$"

variant_count <- 0L
anchor_count <- 0L
for (family in continuous_families) {
  variants <- ggsci_db[[family]]
  if (is.null(variants) || !is.list(variants) || is.null(names(variants))) {
    stop("missing or malformed continuous family: ", family, call. = FALSE)
  }
  function_name <- paste0("rgb_", family)
  if (!exists(function_name, envir = env, inherits = FALSE) ||
      !is.function(env[[function_name]])) {
    stop("canonical continuous function is missing: ", function_name, call. = FALSE)
  }

  for (variant in names(variants)) {
    colors <- variants[[variant]]
    if (!is.character(colors) || anyNA(colors) ||
        any(!grepl(hex_rgb_pattern, colors))) {
      stop("malformed anchor colors: ", family, ":", variant, call. = FALSE)
    }
    variant_count <- variant_count + 1L
    anchor_count <- anchor_count + length(colors)
  }
}

if (variant_count != 53L || anchor_count != 543L) {
  stop(
    "unexpected continuous source counts: variants=", variant_count,
    ", anchors=", anchor_count,
    call. = FALSE
  )
}

canonical_colors <- function(family, variant, n, alpha, reverse) {
  # ggsci's public API errors for n = 0 inside convertColor(). The Rust API
  # intentionally defines this case as empty, so its fixture is explicit.
  if (n == 0L) return(character())

  output <- do.call(
    env[[paste0("rgb_", family)]],
    list(palette = variant, n = n, alpha = alpha, reverse = reverse)
  )
  if (!is.character(output) || length(output) != n || anyNA(output) ||
      any(!grepl(hex_rgba_pattern, output))) {
    stop(
      "malformed canonical output: ", family, ":", variant,
      ", n=", n, ", alpha=", alpha, ", reverse=", reverse,
      call. = FALSE
    )
  }
  toupper(output)
}

rust_string <- function(value) {
  escaped <- gsub("\\\\", "\\\\\\\\", value)
  escaped <- gsub("\"", "\\\\\"", escaped)
  paste0("\"", escaped, "\"")
}

rust_values <- function(colors, rgba = FALSE) {
  if (length(colors) == 0L) return("&[]")
  digits <- if (rgba) substring(colors, 2L, 9L) else substring(colors, 2L, 7L)
  values <- paste0("0x", digits)
  groups <- split(values, ceiling(seq_along(values) / 8L))
  body <- vapply(
    groups,
    function(group) paste0("        ", paste0(group, collapse = ", "), ","),
    character(1L)
  )
  paste(c("&[", body, "    ]"), collapse = "\n")
}

lines <- c(
  "// Generated by tools/generate-continuous-fixtures.R from vendored ggsci.",
  "// Do not edit by hand. No R installation is needed to run these tests.",
  "",
  "pub(crate) struct ContinuousFixture {",
  "    pub(crate) family: &'static str,",
  "    pub(crate) variant: &'static str,",
  "    pub(crate) n: usize,",
  "    pub(crate) forward: &'static [u32],",
  "    pub(crate) reverse: &'static [u32],",
  "}",
  "",
  "pub(crate) struct AlphaFixture {",
  "    pub(crate) family: &'static str,",
  "    pub(crate) variant: &'static str,",
  "    pub(crate) reverse: bool,",
  "    pub(crate) colors: &'static [u32],",
  "}",
  "",
  "pub(crate) static CONTINUOUS_FIXTURES: &[ContinuousFixture] = &["
)

for (family in continuous_families) {
  for (variant in names(ggsci_db[[family]])) {
    for (n in sample_counts) {
      forward <- canonical_colors(family, variant, n, 1, FALSE)
      reverse <- canonical_colors(family, variant, n, 1, TRUE)
      lines <- c(
        lines,
        "    ContinuousFixture {",
        paste0("        family: ", rust_string(family), ","),
        paste0("        variant: ", rust_string(variant), ","),
        paste0("        n: ", n, ","),
        paste0("        forward: ", rust_values(forward), ","),
        paste0("        reverse: ", rust_values(reverse), ","),
        "    },"
      )
    }
  }
}
lines <- c(lines, "];", "", "pub(crate) static ALPHA_FIXTURES: &[AlphaFixture] = &[")

for (family in continuous_families) {
  variant <- representative_variants[[family]]
  if (!(variant %in% names(ggsci_db[[family]]))) {
    stop("representative variant is missing: ", family, ":", variant, call. = FALSE)
  }
  for (reverse in c(FALSE, TRUE)) {
    colors <- canonical_colors(family, variant, 7L, 0.6, reverse)
    lines <- c(
      lines,
      "    AlphaFixture {",
      paste0("        family: ", rust_string(family), ","),
      paste0("        variant: ", rust_string(variant), ","),
      paste0("        reverse: ", tolower(as.character(reverse)), ","),
      paste0("        colors: ", rust_values(colors, rgba = TRUE), ","),
      "    },"
    )
  }
}
lines <- c(lines, "];", "")

dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_file, useBytes = TRUE)
message(
  "generated continuous fixtures for ", variant_count,
  " variants and ", length(sample_counts), " sample counts"
)
