#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
source_root <- if (length(args) >= 1L) args[[1L]] else file.path("vendor", "ggsci")
output_file <- if (length(args) >= 2L) {
  args[[2L]]
} else {
  file.path("crates", "ggsci", "src", "generated", "gephi.rs")
}

palette_file <- file.path(source_root, "R", "palettes.R")
if (!file.exists(palette_file)) {
  stop("palette source not found: ", palette_file, call. = FALSE)
}

env <- new.env(parent = baseenv())
sys.source(palette_file, envir = env)
if (!exists("ggsci_db", envir = env, inherits = FALSE)) {
  stop("palette source did not define ggsci_db", call. = FALSE)
}

ggsci_db <- get("ggsci_db", envir = env, inherits = FALSE)
if (!is.list(ggsci_db) || !is.list(ggsci_db[["gephi"]])) {
  stop("ggsci_db$gephi must be a named list", call. = FALSE)
}

filters <- ggsci_db[["gephi"]]
expected_names <- c(
  "default",
  "fancy_light",
  "fancy_dark",
  "shades",
  "tarnish",
  "pastel",
  "pimp",
  "intense",
  "fluo",
  "red_roses",
  "ochre_sand",
  "yellow_lime",
  "green_mint",
  "ice_cube",
  "blue_ocean",
  "indigo_night",
  "purple_wine"
)
expected_values <- c("hmin", "hmax", "cmin", "cmax", "lmin", "lmax")

if (!identical(names(filters), expected_names)) {
  stop(
    "expected exactly 17 Gephi filters in canonical order: ",
    paste(expected_names, collapse = ", "),
    call. = FALSE
  )
}

normalize_key <- function(value) {
  value <- trimws(value)
  chars <- strsplit(value, "", fixed = TRUE)[[1L]]
  normalized <- vapply(chars, function(ch) {
    if (ch %in% c("_", "-") || grepl("^[[:space:]]$", ch)) {
      " "
    } else {
      tolower(ch)
    }
  }, character(1L), USE.NAMES = FALSE)
  paste0(normalized, collapse = "")
}

normalized_names <- vapply(expected_names, normalize_key, character(1L), USE.NAMES = FALSE)
collision <- anyDuplicated(normalized_names)
if (collision) {
  first <- match(normalized_names[[collision]], normalized_names)
  stop(
    "normalized Gephi filter names collide: ",
    expected_names[[first]], " and ", expected_names[[collision]],
    call. = FALSE
  )
}

rust_string <- function(value) {
  escaped <- gsub("\\\\", "\\\\\\\\", value)
  escaped <- gsub("\"", "\\\\\"", escaped)
  paste0("\"", escaped, "\"")
}

rust_number <- function(value) {
  formatted <- format(value, digits = 15L, scientific = FALSE, trim = TRUE)
  if (!grepl("[.eE]", formatted)) {
    formatted <- paste0(formatted, ".0")
  }
  formatted
}

records <- vector("list", length(filters))
for (index in seq_along(filters)) {
  name <- names(filters)[[index]]
  filter <- filters[[index]]
  if (!is.numeric(filter) || length(filter) != 6L || !identical(names(filter), expected_values)) {
    stop(
      "Gephi filter must contain exactly hmin, hmax, cmin, cmax, lmin, lmax: ",
      name,
      call. = FALSE
    )
  }
  if (anyNA(filter) || any(!is.finite(filter))) {
    stop("Gephi filter contains non-finite values: ", name, call. = FALSE)
  }

  records[[index]] <- list(name = name, values = unname(filter))
}

lines <- c(
  "// Generated by tools/generate-gephi-palettes.R from ggsci/R/palettes.R.",
  "// Do not edit by hand.",
  "",
  "use crate::{GephiFilter, GephiPalette};",
  "",
  paste0("pub(crate) const GEPHI_PALETTE_COUNT: usize = ", length(records), ";"),
  "pub(crate) const GEPHI_DATA_SOURCE: &str = \"ggsci/R/palettes.R\";",
  "",
  "pub(crate) static GEPHI_PALETTES: &[GephiPalette] = &["
)

for (index in seq_along(records)) {
  record <- records[[index]]
  values <- paste(vapply(record$values, rust_number, character(1L)), collapse = ", ")
  lines <- c(
    lines,
    paste0(
      "    GephiPalette::new(", index - 1L, ", ", rust_string(record$name),
      ", GephiFilter::new(", values, ")),"
    )
  )
}
lines <- c(lines, "];", "")

dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_file, useBytes = TRUE)

message("generated ", length(records), " Gephi palette filters")
